package com.etozhesandy.redpanda.core.archive.pipeline

import android.content.Context
import com.etozhesandy.redpanda.core.archive.R
import com.etozhesandy.redpanda.core.archive.extract.ArchiveExtractor
import com.etozhesandy.redpanda.core.archive.format.ArchiveFormatDetector
import com.etozhesandy.redpanda.core.archive.parse.ChatArchiveParserFactory
import com.etozhesandy.redpanda.core.archive.parse.ParseSink
import com.etozhesandy.redpanda.core.archive.scan.OrphanMediaScanner
import com.etozhesandy.redpanda.core.archive.source.ArchiveSource
import com.etozhesandy.redpanda.core.common.dispatcher.IoDispatcher
import com.etozhesandy.redpanda.core.common.files.ProfileDirectories
import com.etozhesandy.redpanda.core.common.importprogress.ImportProgressStore
import com.etozhesandy.redpanda.core.model.Attachment
import com.etozhesandy.redpanda.core.model.ChatDialog
import com.etozhesandy.redpanda.core.model.Friend
import com.etozhesandy.redpanda.core.model.Group
import com.etozhesandy.redpanda.core.model.ImportProgress
import com.etozhesandy.redpanda.core.model.ImportStage
import com.etozhesandy.redpanda.core.model.Message
import com.etozhesandy.redpanda.core.model.ProfileDetails
import com.etozhesandy.redpanda.core.model.ProfileStatus
import com.etozhesandy.redpanda.core.model.SavedPhoto
import com.etozhesandy.redpanda.core.model.Sex
import com.etozhesandy.redpanda.core.model.SourceType
import com.etozhesandy.redpanda.core.storage.db.attachment.AttachmentDao
import com.etozhesandy.redpanda.core.storage.db.attachment.toEntity
import com.etozhesandy.redpanda.core.storage.db.dialog.DialogDao
import com.etozhesandy.redpanda.core.storage.db.dialog.toEntity
import com.etozhesandy.redpanda.core.storage.db.friend.FriendDao
import com.etozhesandy.redpanda.core.storage.db.friend.toEntity
import com.etozhesandy.redpanda.core.storage.db.group.GroupDao
import com.etozhesandy.redpanda.core.storage.db.group.toEntity
import com.etozhesandy.redpanda.core.storage.db.message.MessageDao
import com.etozhesandy.redpanda.core.storage.db.message.toEntity
import com.etozhesandy.redpanda.core.storage.db.profile.ProfileDao
import com.etozhesandy.redpanda.core.storage.db.profile.ProfileEntity
import com.etozhesandy.redpanda.core.storage.db.savedphoto.SavedPhotoDao
import com.etozhesandy.redpanda.core.storage.db.savedphoto.toEntity
import dagger.hilt.android.qualifiers.ApplicationContext
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import javax.inject.Inject
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.flow.flowOn

/**
 * Orchestrates one profile import end to end: copy/extract the archive under
 * `profiles/$id/raw`, detect its format, parse it, and persist everything to Room.
 *
 * Parsers stream their results in batches (a single dialog can run into hundreds of thousands of
 * messages), so this pipeline writes each batch to Room as it arrives instead of collecting the
 * whole archive in memory first. Parsers also process multiple dialogs concurrently, so this uses
 * [channelFlow] (safe for concurrent `send` from many coroutines) instead of the plain `flow {}`
 * builder, whose `emit` is only safe from a single caller at a time.
 */
class ProfileImportPipeline @Inject constructor(
    @ApplicationContext private val context: Context,
    private val extractor: ArchiveExtractor,
    private val formatDetector: ArchiveFormatDetector,
    private val parserFactory: ChatArchiveParserFactory,
    private val directories: ProfileDirectories,
    private val profileDao: ProfileDao,
    private val dialogDao: DialogDao,
    private val messageDao: MessageDao,
    private val attachmentDao: AttachmentDao,
    private val friendDao: FriendDao,
    private val groupDao: GroupDao,
    private val savedPhotoDao: SavedPhotoDao,
    private val progressStore: ImportProgressStore,
    @IoDispatcher private val ioDispatcher: CoroutineDispatcher,
) {

    /** [profileId] is generated by the caller so it's known before the import even starts. */
    fun import(profileId: String, source: ArchiveSource): Flow<ImportProgress> = channelFlow {
        val startedAt = System.currentTimeMillis()
        // Mirrored to the store so any screen can show the same counters the notification does.
        suspend fun emit(progress: ImportProgress) {
            progressStore.publish(profileId, progress)
            send(progress)
        }

        profileDao.upsert(
            ProfileEntity(
                id = profileId,
                sourceType = SourceType.VK,
                displayName = context.getString(R.string.import_profile_name_placeholder),
                avatarPath = null,
                rootDirPath = directories.profileDir(profileId).absolutePath,
                status = ProfileStatus.IMPORTING,
                importedAt = startedAt,
                updatedAt = startedAt,
            ),
        )

        try {
            emit(ImportProgress(ImportStage.COPYING))
            val rawDir = directories.rawDir(profileId)
            extractor.extract(source, rawDir)

            emit(ImportProgress(ImportStage.EXTRACTING))
            val layout = formatDetector.detect(rawDir)
            // A dump with no readable dialog history is still a valid import — plenty are just a
            // folder of photos and videos — so a layout with no parser skips parsing rather than
            // failing the whole import, and the media scan below picks the files up.
            val parser = parserFactory.create(layout.format)

            emit(ImportProgress(ImportStage.PARSING))
            val sink = RoomParseSink { progress -> emit(progress) }
            parser?.parse(layout.contentRoot, profileId, sink)
            messageDao.markMessagesWithAttachments(profileId)

            // Scanning the whole extraction rather than the content root: real dumps keep media
            // outside the folder detection settles on. Labels stay relative to the content root so
            // the media screen's folder names don't gain the wrapper-directory prefix.
            val orphanMedia = OrphanMediaScanner.scan(rawDir, labelRoot = layout.contentRoot)
                .filterNot { it.file.absolutePath in sink.localAttachmentPaths }
                .map { orphan ->
                    Attachment(
                        id = UUID.nameUUIDFromBytes(orphan.file.absolutePath.toByteArray()).toString(),
                        messageId = null,
                        dialogId = "",
                        profileId = profileId,
                        type = orphan.type,
                        path = orphan.file.absolutePath,
                        orderInMessage = 0,
                        timestampEpoch = orphan.file.lastModified(),
                        sourceFolder = orphan.folder,
                    )
                }
            if (orphanMedia.isNotEmpty()) attachmentDao.upsertAll(orphanMedia.map { it.toEntity() })

            val finishedAt = System.currentTimeMillis()
            val details = sink.profileDetails
            profileDao.upsert(
                ProfileEntity(
                    id = profileId,
                    sourceType = SourceType.VK,
                    displayName = sink.displayName
                        ?: layout.contentRoot.name.ifBlank { null }
                        ?: context.getString(R.string.import_profile_name_unknown),
                    avatarPath = details?.avatarPath,
                    rootDirPath = directories.profileDir(profileId).absolutePath,
                    status = ProfileStatus.READY,
                    importedAt = startedAt,
                    updatedAt = finishedAt,
                    vkId = details?.vkId,
                    screenName = details?.screenName,
                    birthDate = details?.birthDate,
                    sex = details?.sex ?: Sex.UNKNOWN,
                    country = details?.country,
                    city = details?.city,
                ),
            )
            emit(
                ImportProgress(
                    ImportStage.DONE,
                    total = sink.savedMessageCount.get(),
                    message = profileId,
                    dialogsDone = sink.dialogsDone.get(),
                    dialogsTotal = sink.dialogsTotal.get(),
                ),
            )
            progressStore.clear(profileId)
        } catch (t: Throwable) {
            profileDao.updateStatus(profileId, ProfileStatus.ERROR, System.currentTimeMillis())
            // Deliberately not cleared: clearing here wiped the failure message on the very next
            // line, leaving "ошибка импорта" with no way to find out what actually went wrong. The
            // snapshot stays until the next import of this profile publishes over it.
            emit(ImportProgress(ImportStage.ERROR, message = t.message))
        }
    }.flowOn(ioDispatcher)

    private inner class RoomParseSink(
        private val emit: suspend (ImportProgress) -> Unit,
    ) : ParseSink {

        @Volatile
        var displayName: String? = null
            private set
        @Volatile
        var profileDetails: ProfileDetails? = null
            private set
        val savedMessageCount = AtomicInteger(0)
        val dialogsTotal = AtomicInteger(0)
        val dialogsDone = AtomicInteger(0)
        val localAttachmentPaths: MutableSet<String> = ConcurrentHashMap.newKeySet()

        override suspend fun onDisplayName(name: String) {
            displayName = name
        }

        override suspend fun onDialogsDiscovered(total: Int) {
            dialogsTotal.set(total)
            emit(saving())
        }

        /** Parsers call this once per dialog, after all of its messages have been streamed in. */
        override suspend fun onDialog(dialog: ChatDialog) {
            dialogDao.upsertAll(listOf(dialog.toEntity()))
            dialogsDone.incrementAndGet()
            emit(saving())
        }

        override suspend fun onMessages(batch: List<Message>) {
            messageDao.upsertAll(batch.map { it.toEntity() })
            savedMessageCount.addAndGet(batch.size)
            emit(saving())
        }

        override suspend fun onAttachments(batch: List<Attachment>) {
            attachmentDao.upsertAll(batch.map { it.toEntity() })
            batch.forEach { attachment ->
                if (!attachment.path.startsWith("http")) localAttachmentPaths += attachment.path
            }
        }

        override suspend fun onProfileDetails(details: ProfileDetails) {
            profileDetails = details
        }

        override suspend fun onFriends(batch: List<Friend>) {
            friendDao.upsertAll(batch.map { it.toEntity() })
        }

        override suspend fun onGroups(batch: List<Group>) {
            groupDao.upsertAll(batch.map { it.toEntity() })
        }

        override suspend fun onSavedPhotos(batch: List<SavedPhoto>) {
            savedPhotoDao.upsertAll(batch.map { it.toEntity() })
        }

        private fun saving() = ImportProgress(
            stage = ImportStage.SAVING,
            current = savedMessageCount.get(),
            dialogsDone = dialogsDone.get(),
            dialogsTotal = dialogsTotal.get(),
        )
    }
}
